name: openedissue

on:
  issues:
    types: [opened]

jobs:
  notify-team:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on Issue
        uses: actions/github-script@v6
        with:
          script: |
            const labels = context.payload.issue.labels
              .map(label => label.name)
              .join(', ');
            
            const labelInfo = labels ? labels : 'unlabeled';
            const issueOwner = context.payload.issue.user.login;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `@PhasesResearchLab/ultera-maintainers: New ${labelInfo} issue at \`ULTERA-contribute\` from ${issueOwner}`
            });